import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "glider-js/glider.min.css";
import Glider from "react-glider";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App (React 18.2.0)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Glider
          hasArrows
          hasDots
          slidesToShow={1}
          slidesToScroll={1}
          className={styles.glider}
        >
          <Image
            src="https://source.unsplash.com/random/600x337?a"
            alt=""
            width={600}
            height={337}
            className={styles.slide}
          />
          <Image
            src="https://source.unsplash.com/random/600x337?b"
            alt=""
            width={600}
            height={337}
            className={styles.slide}
          />
          <Image
            src="https://source.unsplash.com/random/600x337?c"
            alt=""
            width={600}
            height={337}
            className={styles.slide}
          />
        </Glider>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://react-glider.vercel.app/">react-glider!</a>
        </h1>

        <p className={styles.description}>Next 13 / React 18.2.0</p>

        <div className={styles.grid}>
          <a href="https://react-glider.vercel.app/" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about react-glider features and API.</p>
          </a>

          <a href="https://github.com/kevinfarrugia/react-glider" className={styles.card}>
            <h2>Contribute</h2>
            <p>Contribute to react-glider on GitHub</p>
          </a>

          <a
            href="https://codesandbox.io/examples/package/react-glider"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover examples on Code Sandbox</p>
          </a>

          <a
            href="https://www.npmjs.com/package/react-glider"
            className={styles.card}
          >
            <h2>Install &rarr;</h2>
            <p>
              Install using npm or yarn.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
